In [1]:
import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path
import numpy as np
import warnings
from copy import deepcopy

warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=UserWarning)

import constants
import data
import results_gathering
import ml_importance_methods

In [2]:
chemical_data = data.prepare_chemical_data()
chemical_data

,pH,EC,TOC,HCHO,Li,B,Al,V,Cr,Mn,...,Se,Sr,Mo,Sb,Ba,Naftalen,Acenaften,Fluoren,Antracen,Fluoranten
Sample ID,,,,,,,,,,,,,,,,,,,,,
R1_06_17,7.65,48.4,0.450,0.08,0.108,3.145,2.340,0.0230,0.0490,0.0280,...,0.1620,17.3,0.4520,0.0338,3.560,240.9812,4.13820,63.4521,637.8214,258.34780
R1_06_18,7.43,65.2,0.870,0.26,0.158,3.418,2.145,0.0140,0.0740,0.0330,...,0.1760,20.5,0.4010,0.0450,3.870,202.7861,8.41260,68.4871,657.1492,369.72660
R1_09_17,7.20,77.5,1.163,0.04,0.121,2.002,2.700,0.0310,0.0590,0.0130,...,0.1300,20.4,0.3770,0.0251,4.871,426.6419,9.65870,12.3698,201.3681,336.39780
R1_09_18,7.34,74.9,1.120,0.21,0.178,2.012,3.147,0.0470,0.0680,0.0140,...,0.1450,35.1,0.1720,0.0217,5.010,205.6584,8.11230,70.1548,652.1478,351.16230
R2_06_17,7.43,92.7,0.975,0.08,0.728,2.981,3.890,0.0440,0.0670,0.0210,...,0.1180,19.8,0.1410,0.0335,3.440,321.2831,7.92810,62.3901,128.3982,28.30190
R2_06_18,7.83,89.3,1.103,0.13,0.928,2.891,2.790,0.0884,0.1350,0.1280,...,0.1500,20.8,0.3720,0.0385,18.400,329.3910,6.93050,64.8915,133.9510,40.84870
R2_09_17,7.13,80.3,1.294,0.04,0.632,2.391,3.920,0.0390,0.0610,0.0220,...,0.1530,28.8,0.1820,0.0264,2.990,543.3130,10.23810,11.2313,201.8430,30.90110
R2_09_18,7.13,84.7,1.167,0.12,0.583,2.389,14.100,0.0705,0.1150,0.2360,...,0.1300,30.0,0.2170,0.0260,11.200,458.9635,7.24710,66.7428,135.8640,56.97520
R3_06_17,7.51,101.7,0.692,0.06,0.625,2.147,5.660,0.1100,0.0690,0.0580,...,0.1660,43.2,0.4190,0.0864,7.040,145.9878,3.69720,61.8971,45.3698,32.36070
R3_06_18,7.49,98.8,0.710,0.16,0.578,3.012,3.987,0.0230,0.0390,0.0390,...,0.1140,56.4,0.0904,0.0283,9.320,148.9621,13.65210,80.4991,50.4826,45.51910
R3_09_17,7.18,110.4,1.143,0.04,0.513,2.631,10.400,0.0580,0.2100,0.0550,...,0.1820,44.5,0.4090,0.0277,6.118,238.9416,3.96250,116.3987,363.3978,201.31780
R3_09_18,7.16,108.4,1.480,0.18,0.489,2.441,7.989,0.0920,0.1700,0.0570,...,0.1200,49.6,0.1970,0.0263,5.961,178.3215,5.24780,74.1654,52.0016,41.92660
R4_06_17,7.29,83.1,0.989,0.08,0.232,3.068,2.580,0.0400,0.0630,0.0310,...,0.1260,27.2,0.1540,0.0178,8.760,112.6870,11.58910,58.2651,402.9812,256.89410
R4_06_18,7.65,84.1,0.910,0.28,0.193,2.514,2.100,0.0410,0.0550,0.0120,...,0.1320,35.2,0.2700,0.0305,7.120,165.3698,11.58470,21.8749,568.1489,308.91960
R4_09_17,7.19,87.2,1.107,0.15,0.273,2.162,12.400,0.0620,0.0240,0.0650,...,0.1510,34.3,0.3230,0.0243,6.471,451.0210,16.39780,349.6771,301.2584,997.18960
R4_09_18,7.26,79.2,1.450,0.25,0.257,2.924,9.452,0.0780,0.0390,0.0780,...,0.1560,26.9,0.2200,0.0248,7.003,164.3289,11.78310,328.4102,512.9498,267.19960
R5_06_17,7.24,85.1,0.973,0.16,0.269,3.078,5.120,0.0430,0.0520,0.0210,...,0.1040,31.3,0.2700,0.0194,9.820,134.9182,10.38910,61.2911,401.3911,199.28910
R5_06_18,7.25,82.7,0.928,0.18,0.382,3.092,4.850,0.1060,0.1430,0.0834,...,0.2030,30.9,0.3060,0.0301,10.300,138.9750,17.74390,56.9739,473.8790,146.96300
R5_09_17,7.05,90.5,1.231,0.27,0.273,2.998,9.170,0.0430,0.0610,0.3700,...,0.1410,35.0,0.2980,0.0269,11.500,293.9380,12.49520,172.9010,432.9810,204.91200
R5_09_18,7.93,92.8,1.112,0.21,0.387,2.114,5.050,0.0264,0.1150,0.0757,...,0.1560,25.1,0.2740,0.0358,6.790,268.9632,16.98750,205.9721,504.9811,382.88950
R6_06_17,7.38,86.2,0.773,0.08,0.293,3.065,8.830,0.0420,0.0470,0.0340,...,0.1460,31.4,0.2830,0.0223,10.200,184.9380,9.28910,63.9371,403.4155,107.28910
R6_06_18,7.91,82.9,0.842,0.09,0.331,3.901,10.700,0.0884,0.1430,0.5630,...,0.1410,35.5,0.2890,0.0339,10.900,205.9640,21.97430,67.4289,432.9750,95.85300
R6_09_17,7.12,91.1,1.103,0.03,0.272,2.452,11.080,0.0460,0.0490,0.0320,...,0.1810,35.5,0.3070,0.0270,11.000,301.8640,10.95320,113.0820,541.0330,113.89200
R6_09_18,7.33,90.6,1.268,0.09,0.232,3.024,4.920,0.0479,0.0835,0.0577,...,0.1270,39.5,0.2260,0.0260,10.700,321.9864,12.97630,115.9864,492.9743,163.89610
R7_06_17,7.28,88.5,1.015,0.05,0.303,2.097,5.790,0.0430,0.0540,0.0580,...,0.1380,31.7,0.3040,0.0510,10.600,298.3910,9.29710,60.3891,294.1830,99.89110
R7_06_18,7.73,83.1,1.013,0.03,0.398,3.126,6.830,0.0579,0.1070,0.1440,...,0.1390,24.6,0.1850,0.0245,9.820,336.9430,8.86430,58.9742,345.9740,88.53290
R7_09_17,7.04,100.2,1.373,0.15,0.388,2.078,5.940,0.0480,0.0410,0.0650,...,0.0985,61.7,0.2530,0.0880,9.780,490.3900,11.84593,145.8210,309.1930,104.99310
R7_09_18,7.09,95.2,1.975,0.11,0.392,2.491,4.220,0.0430,0.1010,0.0397,...,0.1510,28.8,0.2190,0.0277,8.700,369.4216,13.08530,184.0501,284.0699,163.79530
R8_06_17,7.19,133.8,1.380,0.08,0.368,3.014,3.750,0.0280,0.0890,0.0310,...,0.1040,48.8,0.1970,0.0212,8.820,178.9380,9.29110,58.3113,211.3980,92.39153
R8_06_18,7.24,104.9,0.974,0.08,0.391,3.029,8.960,0.0587,0.2400,0.1680,...,0.1230,28.3,0.2250,0.0262,10.800,268.6430,8.85220,64.9643,128.8640,89.75320
R8_09_17,7.22,117.9,0.887,0.03,0.387,3.027,3.650,0.0240,0.0840,0.0320,...,0.1580,40.7,0.3250,0.0236,9.300,389.3890,14.93710,118.9310,249.1160,105.87170
R8_09_18,7.42,127.1,1.230,0.07,0.375,4.314,4.220,0.0414,0.1080,0.1520,...,0.1720,54.2,0.2190,0.0279,9.690,368.4393,15.08760,126.0842,284.3579,98.86320

In [3]:
class_data, indices_to_names = data.prepare_class_data()
class_data

,R1_06_17,R1_06_18,R1_09_17,R1_09_18,R2_06_17,R2_06_18,R2_09_17,R2_09_18,R3_06_17,R3_06_18,...,R6_09.17,R6_09_18,R7_06_17,R7_06_18,R7_09_17,R7_09_18,R8_06_17,R8_06_18,R8_09_17,R8_09_18
3,4,6,2,0,2,5,3,10,0,0,...,0,0,2,0,0,2,0,0,0,0
4,1,1,2,2,15,2,9,2,8,2,...,0,0,8,2,0,0,11,0,1,2
8,38,10,54,17,66,31,28,12,15,4,...,2,1,42,13,0,14,9,5,11,1
10,179,125,329,54,287,252,319,124,159,91,...,5,61,174,136,0,69,151,134,75,118
13,3,1,5,3,5,3,5,0,0,0,...,0,0,2,0,0,5,0,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,210,110,7433,7072,535,151,896,8234,92,502,...,352,18987,1123,19666,29,3699,543,517,2590,409
163,2,0,4,2,8,5,5,2,0,0,...,0,0,3,1,0,2,2,1,0,1
169,0,4,15,3,27,24,11,1,2,2,...,0,16,29,14,0,14,25,5,20,21
170,7,1,4,4,3,3,0,0,0,2,...,0,0,0,0,0,4,1,1,5,1
173,32,46,98,32,177,214,220,34,99,79,...,3,20,85,31,0,45,193,83,73,93

In [4]:
decition_tree_importance = results_gathering.important_relationships_for_all_bacteria(
    chemical_data,
    class_data,
    ml_importance_methods.get_decision_tree_importance,
    model_name="decision_tree",
    importance_threshold=0.9)
results_to_display_decision_tree = deepcopy(decition_tree_importance)
names = results_gathering.name_lookup(list(results_to_display_decision_tree['Bacteria']), indices_to_names)
results_to_display_decision_tree['Bacteria'] = names
results_to_display_decision_tree

,Bacteria,Chemicals,Importance_decision_tree,CV_decision_tree,R_squared_decision_tree
0,Deinococci,Acenaften,1.003978,-390.036202,0.514666
1,BPC102,Ba,1.004935,-5.915186,0.354569
2,Acidimicrobiia,HCHO,0.995704,-4.978949,0.543093
3,MB-A2-108,Ba,0.926643,-4.855150,0.442917
4,[Fimbriimonadia],Rb,1.781893,-0.298578,0.492496
...,...,...,...,...,...
89,Opitutae,Sb,1.423738,-4.863299,-0.552177
90,Opitutae,Ba,1.423738,-4.863299,-0.552177
91,Opitutae,Naftalen,1.423738,-4.863299,-0.552177
92,Opitutae,Acenaften,1.423738,-4.863299,-0.552177
93,Verrucomicrobiae,Sb,1.393798,-8.720502,0.616033

In [5]:
sorted_decition_tree_importance = decition_tree_importance.sort_values("R_squared_decision_tree", ascending=False)
sorted_decition_tree_importance

,Bacteria,Chemicals,Importance_decision_tree,CV_decision_tree,R_squared_decision_tree
65,46,Rb,1.309942,-4.915672,0.931402
8,33,Sb,1.322649,-2.571363,0.789356
70,60,Rb,1.346290,-2.278675,0.786545
69,58,Rb,0.902380,-4.547151,0.737009
9,35,Ba,1.080226,-12.207380,0.723164
...,...,...,...,...,...
59,42,Ga,1.891378,-8491.193810,-0.965350
60,42,Rb,1.891378,-8491.193810,-0.965350
61,42,Sb,1.891378,-8491.193810,-0.965350
62,42,Ba,1.891378,-8491.193810,-0.965350
47,42,"[Cr, Fe]",1.972396,-8491.193810,-0.965350

In [6]:
xgboost_feature_importance = results_gathering.important_relationships_for_all_bacteria(
    chemical_data,
    class_data,
    ml_importance_methods.get_xgboost_importance,
    model_name="xgboost",
    importance_threshold=0.9)
results_to_display_xgboost = deepcopy(xgboost_feature_importance)
names = results_gathering.name_lookup(list(results_to_display_xgboost['Bacteria']), indices_to_names)
results_to_display_xgboost['Bacteria'] = names
results_to_display_xgboost

,Bacteria,Chemicals,Importance_xgboost,CV_xgboost,R_squared_xgboost
0,Deinococci,"[TOC, Fluoren]",0.931765,-1075.289667,0.064839
1,Deinococci,"[V, As]",0.932538,-1075.289667,0.064839
2,Deinococci,"[Cr, Fe]",0.931849,-1075.289667,0.064839
3,Deinococci,"[Mn, Fe]",0.931751,-1075.289667,0.064839
4,Deinococci,"[Se, Mo]",1.870632,-1075.289667,0.064839
...,...,...,...,...,...
98,{Unknown Class} Kazan-3B-28,Rb,1.722686,-15.677974,0.971198
99,{Unknown Class} SR1,Rb,1.742829,-0.946330,0.895683
100,TM7-3,"[Fe, Al, Cr, Mn]",0.977134,-5.897372,0.629226
101,TM7-3,EC,0.986634,-5.897372,0.629226
102,TM7-3,Sb,0.994114,-5.897372,0.629226

In [7]:
random_forest_feature_importance = results_gathering.important_relationships_for_all_bacteria(
    chemical_data,
    class_data,
    ml_importance_methods.get_random_forest_importance,
    model_name="random_forest",
    importance_threshold=0.15)
results_to_display_rf = deepcopy(random_forest_feature_importance)
names = results_gathering.name_lookup(list(results_to_display_rf['Bacteria']), indices_to_names)
results_to_display_rf['Bacteria'] = names
results_to_display_rf

,Bacteria,Chemicals,Importance_random_forest,CV_random_forest,R_squared_random_forest
0,Deinococci,"[Fe, Al, Cr, Mn]",0.161459,-0.344655,0.405489
1,Deinococci,"[Se, Mo]",0.160894,-0.344655,0.405489
2,Deinococci,"[Fluoren, Fluoranten]",0.162715,-0.344655,0.405489
3,Deinococci,pH,0.162713,-0.344655,0.405489
4,Deinococci,EC,0.162533,-0.344655,0.405489
...,...,...,...,...,...
244,TM7-1,Sb,0.185871,-0.052531,0.569642
245,TM7-3,Sb,0.289554,-0.115427,0.592545
246,{Unknown Class} Verrucomicrobia,Naftalen,0.164864,-0.106171,0.656971
247,{Unknown Class} WPS-2,Sr,0.165875,0.090505,0.704758
248,SC72,Sr,0.156009,0.001269,0.568897

In [8]:
final_results = results_gathering.prepare_final_results(
    chemical_data,
    class_data,
    decition_tree_importance,
    xgboost_feature_importance,
    random_forest_feature_importance,
)
names = results_gathering.name_lookup(list(final_results['Bacteria']), indices_to_names)
final_results['Bacteria'] = names
final_results

,Bacteria,Chemicals,Bacteria_counts,Correlation,Importance_random_forest,CV_random_forest,R_squared_random_forest,Importance_xgboost,CV_xgboost,R_squared_xgboost,Importance_decision_tree,CV_decision_tree,R_squared_decision_tree
0,Deinococci,Acenaften,273,-0.331219,0.231002,-0.344655,0.405489,2.045194,-1075.289667,0.064839,1.003978,-390.036202,0.514666
1,SAR202,B,89,-0.240631,0.265418,-0.122337,0.551902,1.105115,-0.318247,0.748351,1.492544,0.081737,0.691383
2,4C0d-2,Sb,373,-0.278007,0.339576,0.059501,0.616159,1.357176,-1.222224,0.838606,1.322649,-2.571363,0.789356
3,Oscillatoriophycideae,Sb,6777,-0.162584,0.388508,-0.208812,0.480250,1.189555,-694.661326,0.925877,1.038573,-156.773969,-0.408531
4,Synechococcophycideae,Sb,3124,-0.129342,0.406600,-0.228579,0.487818,1.311605,-106.077728,0.852756,1.100337,-62.856875,0.402677
5,Clostridia,"['Fe', 'Al', 'Cr', 'Mn']",5813,-0.165999,0.174737,-0.270152,0.235340,1.224798,-325.829868,-0.061185,0.959687,-17.980553,-0.567062
6,Clostridia,HCHO,5813,-0.040685,0.200002,-0.270152,0.235340,1.064938,-325.829868,-0.061185,0.982423,-17.980553,-0.567062
7,Clostridia,B,5813,-0.017070,0.207184,-0.270152,0.235340,1.060935,-325.829868,-0.061185,0.982423,-17.980553,-0.567062
8,Clostridia,Ni,5813,-0.043579,0.203966,-0.270152,0.235340,1.068220,-325.829868,-0.061185,0.982423,-17.980553,-0.567062
9,Clostridia,Ga,5813,0.067043,0.195248,-0.270152,0.235340,1.061400,-325.829868,-0.061185,0.982423,-17.980553,-0.567062
10,Clostridia,Rb,5813,-0.183033,0.218907,-0.270152,0.235340,1.092870,-325.829868,-0.061185,0.982423,-17.980553,-0.567062
11,Clostridia,Sb,5813,-0.063426,0.237712,-0.270152,0.235340,1.059530,-325.829868,-0.061185,0.984849,-17.980553,-0.567062
12,Clostridia,Ba,5813,0.033448,0.203078,-0.270152,0.235340,1.065930,-325.829868,-0.061185,0.982423,-17.980553,-0.567062
13,Clostridia,Naftalen,5813,-0.105206,0.201292,-0.270152,0.235340,1.071429,-325.829868,-0.061185,0.982423,-17.980553,-0.567062
14,Clostridia,Acenaften,5813,0.016033,0.195269,-0.270152,0.235340,1.058486,-325.829868,-0.061185,0.982423,-17.980553,-0.567062
15,{Unknown Class} Kazan-3B-28,Rb,155,-0.268886,0.400615,-0.022276,0.432552,1.722686,-15.677974,0.971198,1.228029,-1.603547,0.576143
16,{Unknown Class} SR1,Rb,295,-0.475288,0.471170,0.143261,0.579459,1.742829,-0.946330,0.895683,1.972468,-1.683654,0.700084
17,TM7-3,Sb,2900,-0.243166,0.289554,-0.115427,0.592545,0.994114,-5.897372,0.629226,1.004267,-7.067268,0.693896

In [9]:
decition_tree_importance.to_csv("./results/class_analysis_decision_tree.csv")
xgboost_feature_importance.to_csv("./results/class_analysis_xgboost.csv")
random_forest_feature_importance.to_csv("./results/class_analysis_rf.csv")