In [1]:
import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=UserWarning)

import constants
import data
import results_gathering
import ml_importance_methods

In [2]:
chemical_data = data.prepare_chemical_data()
chemical_data

,pH,EC,TOC,HCHO,Li,B,Al,V,Cr,Mn,...,Se,Sr,Mo,Sb,Ba,Naftalen,Acenaften,Fluoren,Antracen,Fluoranten
Sample ID,,,,,,,,,,,,,,,,,,,,,
R1_06_17,7.65,48.4,0.450,0.08,0.108,3.145,2.340,0.0230,0.0490,0.0280,...,0.1620,17.3,0.4520,0.0338,3.560,240.9812,4.13820,63.4521,637.8214,258.34780
R1_06_18,7.43,65.2,0.870,0.26,0.158,3.418,2.145,0.0140,0.0740,0.0330,...,0.1760,20.5,0.4010,0.0450,3.870,202.7861,8.41260,68.4871,657.1492,369.72660
R1_09_17,7.20,77.5,1.163,0.04,0.121,2.002,2.700,0.0310,0.0590,0.0130,...,0.1300,20.4,0.3770,0.0251,4.871,426.6419,9.65870,12.3698,201.3681,336.39780
R1_09_18,7.34,74.9,1.120,0.21,0.178,2.012,3.147,0.0470,0.0680,0.0140,...,0.1450,35.1,0.1720,0.0217,5.010,205.6584,8.11230,70.1548,652.1478,351.16230
R2_06_17,7.43,92.7,0.975,0.08,0.728,2.981,3.890,0.0440,0.0670,0.0210,...,0.1180,19.8,0.1410,0.0335,3.440,321.2831,7.92810,62.3901,128.3982,28.30190
R2_06_18,7.83,89.3,1.103,0.13,0.928,2.891,2.790,0.0884,0.1350,0.1280,...,0.1500,20.8,0.3720,0.0385,18.400,329.3910,6.93050,64.8915,133.9510,40.84870
R2_09_17,7.13,80.3,1.294,0.04,0.632,2.391,3.920,0.0390,0.0610,0.0220,...,0.1530,28.8,0.1820,0.0264,2.990,543.3130,10.23810,11.2313,201.8430,30.90110
R2_09_18,7.13,84.7,1.167,0.12,0.583,2.389,14.100,0.0705,0.1150,0.2360,...,0.1300,30.0,0.2170,0.0260,11.200,458.9635,7.24710,66.7428,135.8640,56.97520
R3_06_17,7.51,101.7,0.692,0.06,0.625,2.147,5.660,0.1100,0.0690,0.0580,...,0.1660,43.2,0.4190,0.0864,7.040,145.9878,3.69720,61.8971,45.3698,32.36070
R3_06_18,7.49,98.8,0.710,0.16,0.578,3.012,3.987,0.0230,0.0390,0.0390,...,0.1140,56.4,0.0904,0.0283,9.320,148.9621,13.65210,80.4991,50.4826,45.51910
R3_09_17,7.18,110.4,1.143,0.04,0.513,2.631,10.400,0.0580,0.2100,0.0550,...,0.1820,44.5,0.4090,0.0277,6.118,238.9416,3.96250,116.3987,363.3978,201.31780
R3_09_18,7.16,108.4,1.480,0.18,0.489,2.441,7.989,0.0920,0.1700,0.0570,...,0.1200,49.6,0.1970,0.0263,5.961,178.3215,5.24780,74.1654,52.0016,41.92660
R4_06_17,7.29,83.1,0.989,0.08,0.232,3.068,2.580,0.0400,0.0630,0.0310,...,0.1260,27.2,0.1540,0.0178,8.760,112.6870,11.58910,58.2651,402.9812,256.89410
R4_06_18,7.65,84.1,0.910,0.28,0.193,2.514,2.100,0.0410,0.0550,0.0120,...,0.1320,35.2,0.2700,0.0305,7.120,165.3698,11.58470,21.8749,568.1489,308.91960
R4_09_17,7.19,87.2,1.107,0.15,0.273,2.162,12.400,0.0620,0.0240,0.0650,...,0.1510,34.3,0.3230,0.0243,6.471,451.0210,16.39780,349.6771,301.2584,997.18960
R4_09_18,7.26,79.2,1.450,0.25,0.257,2.924,9.452,0.0780,0.0390,0.0780,...,0.1560,26.9,0.2200,0.0248,7.003,164.3289,11.78310,328.4102,512.9498,267.19960
R5_06_17,7.24,85.1,0.973,0.16,0.269,3.078,5.120,0.0430,0.0520,0.0210,...,0.1040,31.3,0.2700,0.0194,9.820,134.9182,10.38910,61.2911,401.3911,199.28910
R5_06_18,7.25,82.7,0.928,0.18,0.382,3.092,4.850,0.1060,0.1430,0.0834,...,0.2030,30.9,0.3060,0.0301,10.300,138.9750,17.74390,56.9739,473.8790,146.96300
R5_09_17,7.05,90.5,1.231,0.27,0.273,2.998,9.170,0.0430,0.0610,0.3700,...,0.1410,35.0,0.2980,0.0269,11.500,293.9380,12.49520,172.9010,432.9810,204.91200
R5_09_18,7.93,92.8,1.112,0.21,0.387,2.114,5.050,0.0264,0.1150,0.0757,...,0.1560,25.1,0.2740,0.0358,6.790,268.9632,16.98750,205.9721,504.9811,382.88950
R6_06_17,7.38,86.2,0.773,0.08,0.293,3.065,8.830,0.0420,0.0470,0.0340,...,0.1460,31.4,0.2830,0.0223,10.200,184.9380,9.28910,63.9371,403.4155,107.28910
R6_06_18,7.91,82.9,0.842,0.09,0.331,3.901,10.700,0.0884,0.1430,0.5630,...,0.1410,35.5,0.2890,0.0339,10.900,205.9640,21.97430,67.4289,432.9750,95.85300
R6_09_17,7.12,91.1,1.103,0.03,0.272,2.452,11.080,0.0460,0.0490,0.0320,...,0.1810,35.5,0.3070,0.0270,11.000,301.8640,10.95320,113.0820,541.0330,113.89200
R6_09_18,7.33,90.6,1.268,0.09,0.232,3.024,4.920,0.0479,0.0835,0.0577,...,0.1270,39.5,0.2260,0.0260,10.700,321.9864,12.97630,115.9864,492.9743,163.89610
R7_06_17,7.28,88.5,1.015,0.05,0.303,2.097,5.790,0.0430,0.0540,0.0580,...,0.1380,31.7,0.3040,0.0510,10.600,298.3910,9.29710,60.3891,294.1830,99.89110
R7_06_18,7.73,83.1,1.013,0.03,0.398,3.126,6.830,0.0579,0.1070,0.1440,...,0.1390,24.6,0.1850,0.0245,9.820,336.9430,8.86430,58.9742,345.9740,88.53290
R7_09_17,7.04,100.2,1.373,0.15,0.388,2.078,5.940,0.0480,0.0410,0.0650,...,0.0985,61.7,0.2530,0.0880,9.780,490.3900,11.84593,145.8210,309.1930,104.99310
R7_09_18,7.09,95.2,1.975,0.11,0.392,2.491,4.220,0.0430,0.1010,0.0397,...,0.1510,28.8,0.2190,0.0277,8.700,369.4216,13.08530,184.0501,284.0699,163.79530
R8_06_17,7.19,133.8,1.380,0.08,0.368,3.014,3.750,0.0280,0.0890,0.0310,...,0.1040,48.8,0.1970,0.0212,8.820,178.9380,9.29110,58.3113,211.3980,92.39153
R8_06_18,7.24,104.9,0.974,0.08,0.391,3.029,8.960,0.0587,0.2400,0.1680,...,0.1230,28.3,0.2250,0.0262,10.800,268.6430,8.85220,64.9643,128.8640,89.75320
R8_09_17,7.22,117.9,0.887,0.03,0.387,3.027,3.650,0.0240,0.0840,0.0320,...,0.1580,40.7,0.3250,0.0236,9.300,389.3890,14.93710,118.9310,249.1160,105.87170
R8_09_18,7.42,127.1,1.230,0.07,0.375,4.314,4.220,0.0414,0.1080,0.1520,...,0.1720,54.2,0.2190,0.0279,9.690,368.4393,15.08760,126.0842,284.3579,98.86320

In [3]:
type_data, indices_to_names = data.prepare_type_data()
type_data

,R1_06_17,R1_06_18,R1_09_17,R1_09_18,R2_06_17,R2_06_18,R2_09_17,R2_09_18,R3_06_17,R3_06_18,...,R6_09.17,R6_09_18,R7_06_17,R7_06_18,R7_09_17,R7_09_18,R8_06_17,R8_06_18,R8_09_17,R8_09_18
0,5295,6955,6790,9538,5190,3890,6346,14767,12348,9805,...,42749,10311,8881,6381,48365,8064,5965,5949,5965,10972
1,306,153,7608,7120,781,404,1113,9394,836,3137,...,664,20841,1831,19973,29,7017,643,570,3781,2226
2,4613,960,3717,17088,1401,1319,1281,8144,9858,1506,...,12857,366,1918,2202,4138,858,3346,1103,433,1131
3,1109,602,1211,518,1725,1321,3451,2152,2671,4177,...,203,2832,4261,10346,11,2590,925,5868,2089,2764
4,14154,16815,2872,895,3760,8078,3018,2353,2318,1386,...,67,310,4391,209,66,347,1171,112,451,603
5,1686,1964,4393,1443,3532,3490,4302,1203,2461,2735,...,56,821,1145,683,2,2135,3804,3623,2091,3149
6,51,30,141,39,154,72,168,573,856,968,...,229,1963,3051,1644,3,374,173,36,768,431
7,62,65,174,170,554,230,1484,83,70,827,...,91,630,1106,1922,59,604,140,314,413,153
8,145,425,322,114,834,1123,584,179,206,183,...,50,385,1176,328,4,452,1439,1069,903,548
9,259,159,455,99,423,352,406,155,193,108,...,7,66,243,159,0,91,170,144,94,125
10,220,146,258,132,331,265,384,179,116,65,...,6,70,292,131,0,95,129,161,163,112
11,25,55,94,33,298,264,285,31,113,76,...,7,85,254,124,0,158,354,168,439,158
12,97,67,382,194,205,220,317,83,39,40,...,1,65,51,43,3,252,473,243,167,315
13,32,46,98,32,177,214,220,34,99,79,...,3,20,85,31,0,45,193,83,73,93
14,10,9,45,14,89,41,92,6,4,15,...,5,113,147,57,0,54,69,48,115,23
15,69,65,48,20,141,128,164,58,83,44,...,0,2,21,23,0,21,36,41,20,36
16,6,10,31,6,43,12,43,16,0,10,...,4,52,94,32,0,26,130,60,85,33
17,141,49,183,67,87,66,136,25,34,14,...,0,1,8,0,0,12,34,27,10,40
18,0,2,4,1,311,321,64,3,11,2,...,0,1,22,3,0,2,0,1,0,1
19,44,34,109,19,25,30,28,5,15,12,...,1,0,21,3,0,4,17,4,0,14
20,7,7,19,7,34,27,11,1,3,5,...,0,16,29,14,0,18,26,6,27,24
21,25,18,20,1,38,50,48,7,31,13,...,0,1,6,0,0,9,11,8,6,17
22,9,2,12,0,3,4,0,2,6,2,...,0,8,0,12,0,13,38,36,26,64
23,1,1,2,2,15,2,9,2,8,2,...,0,0,8,2,0,0,11,0,1,2
24,2,7,12,19,20,41,6,2,0,0,...,0,0,2,0,0,0,0,0,0,0
25,0,0,5,1,5,3,6,0,0,0,...,0,2,4,4,0,0,54,19,15,9
26,0,0,2,2,8,6,6,3,11,5,...,0,3,0,4,0,2,17,0,3,7
27,3,1,3,0,13,11,26,5,13,4,...,0,0,3,1,0,0,2,1,2,5
28,4,4,0,0,16,21,2,1,10,0,...,0,0,8,0,0,0,1,0,1,2
29,4,6,2,0,2,5,3,10,0,0,...,0,0,2,0,0,2,0,0,0,0
30,3,1,4,0,15,5,2,0,0,0,...,0,0,1,1,0,0,4,4,0,0
31,2,0,4,2,8,5,5,2,0,0,...,0,0,3,1,0,2,2,1,0,1
32,4,0,8,2,3,2,3,0,2,0,...,0,0,0,0,0,6,2,4,0,0
33,0,0,0,0,4,9,1,0,2,0,...,0,0,2,0,0,0,2,0,0,0
34,2,0,6,0,1,0,3,0,0,0,...,0,0,0,0,0,0,6,0,1,3
35,0,0,0,0,0,0,0,0,0,0,...,0,0,4,0,0,0,0,0,0,0
36,0,0,0,0,1,0,1,2,0,0,...,0,3,3,5,0,5,0,0,0,0
37,2,0,4,0,4,4,3,3,0,0,...,0,0,0,2,0,0,0,0,2,0
38,0,0,0,0,2,7,1,0,0,0,...,0,0,2,2,0,0,2,0,0,0
39,0,0,0,0,0,0,0,0,0,0,...,0,3,0,0,0,0,0,0,2,0
40,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,4,5,0,2
41,0,0,2,0,2,0,0,0,0,0,...,0,0,3,0,0,3,2,0,0,0
42,0,0,0,0,0,4,0,0,0,0,...,0,0,0,0,0,0,2,2,0,4
43,0,0,2,0,0,0,0,2,1,0,...,0,0,2,2,0,0,0,2,0,0
44,3,0,5,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45,0,0,0,0,3,1,3,0,0,0,...,0,0,0,0,0,0,2,2,0,0
46,0,0,0,0,0,0,0,4,0,0,...,0,0,0,0,0,0,2,2,1,0
47,0,0,0,0,0,0,0,0,0,2,...,0,0,1,2,0,0,0,2,0,0
48,0,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49,2,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50,0,0,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,2,0
51,0,0,0,0,0,0,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
52,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
53,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
decition_tree_importance = results_gathering.important_relationships_for_all_bacteria(
    chemical_data,
    type_data,
    ml_importance_methods.get_decision_tree_importance,
    model_name="decition_tree",
    importance_threshold=0.9)
names = results_gathering.name_lookup(list(decition_tree_importance ['Bacteria']), indices_to_names)
decition_tree_importance ['Bacteria'] = names
decition_tree_importance

,Bacteria,Chemicals,Importance_decition_tree,CV_decition_tree,R_squared_decition_tree
0,2,"[EC, Sr, Antracen]",1.055014,-3.484160,-0.383850
1,2,"[Li, Antracen]",1.055014,-3.484160,-0.383850
2,2,"[Al, Fe]",1.055014,-3.484160,-0.383850
3,2,"[V, As]",1.055014,-3.484160,-0.383850
4,2,"[Cr, Fe]",1.055014,-3.484160,-0.383850
...,...,...,...,...,...
68,52,Rb,1.032258,0.366667,-0.548387
69,52,Sb,1.032258,0.366667,-0.548387
70,52,Ba,1.032258,0.366667,-0.548387
71,52,Naftalen,1.032258,0.366667,-0.548387
72,52,Acenaften,1.032258,0.366667,-0.548387

In [5]:
xgboost_feature_importance = results_gathering.important_relationships_for_all_bacteria(
    chemical_data,
    type_data,
    ml_importance_methods.get_xgboost_importance,
    model_name="xgboost",
    importance_threshold=0.9)
names = results_gathering.name_lookup(list(xgboost_feature_importance['Bacteria']), indices_to_names)
xgboost_feature_importance['Bacteria'] = names
xgboost_feature_importance

,Bacteria,Chemicals,Importance_xgboost,CV_xgboost,R_squared_xgboost
0,22,Rb,1.436011,-0.749965,0.931724
1,23,"[Li, Antracen]",1.880251,-40.791407,0.046522
2,23,"[V, As]",0.945190,-40.791407,0.046522
3,23,"[Cr, Fe]",1.887524,-40.791407,0.046522
4,23,"[Mn, Fe]",1.887712,-40.791407,0.046522
...,...,...,...,...,...
78,53,Sr,1.372612,-0.040000,-0.372614
79,53,Sb,1.372612,-0.040000,-0.372614
80,53,Ba,1.372612,-0.040000,-0.372614
81,53,Naftalen,1.372612,-0.040000,-0.372614
82,53,Acenaften,1.538376,-0.040000,-0.372614

In [6]:
random_forest_feature_importance = results_gathering.important_relationships_for_all_bacteria(
    chemical_data,
    type_data,
    ml_importance_methods.get_random_forest_importance,
    model_name="random_forest",
    importance_threshold=0.15)
names = results_gathering.name_lookup(list(random_forest_feature_importance['Bacteria']), indices_to_names)
random_forest_feature_importance['Bacteria'] = names
random_forest_feature_importance

,Bacteria,Chemicals,Importance_random_forest,CV_random_forest,R_squared_random_forest
0,2,B,0.177597,-0.761490,0.530900
1,2,Rb,0.178150,-0.761490,0.530900
2,2,Acenaften,0.157245,-0.761490,0.530900
3,7,"[Fe, Al, Cr, Mn]",0.158995,-3.950316,0.610758
4,8,Ga,0.157452,-0.551250,0.539490
...,...,...,...,...,...
110,53,Sr,0.251325,-0.040000,0.299685
111,53,Sb,0.230245,-0.040000,0.299685
112,53,Ba,0.235804,-0.040000,0.299685
113,53,Naftalen,0.234455,-0.040000,0.299685
114,53,Acenaften,0.256129,-0.040000,0.299685

In [7]:
final_results = results_gathering.prepare_final_results(
    chemical_data,
    type_data,
    decition_tree_importance,
    xgboost_feature_importance,
    random_forest_feature_importance
)
names = results_gathering.name_lookup(list(final_results['Bacteria']), indices_to_names)
final_results['Bacteria'] = names
final_results

,Bacteria,Chemicals,Bacteria_counts,Correlation,Importance_random_forest,CV_random_forest,R_squared_random_forest,Importance_xgboost,CV_xgboost,R_squared_xgboost,Importance_decition_tree,CV_decition_tree,R_squared_decition_tree
0,22,Rb,295,-0.436561,0.361337,-4.427513,0.620888,1.436011,-0.749965,0.931724,1.937845,-1.955304,0.800314
1,23,Acenaften,273,-0.333717,0.205872,-56.776110,0.452574,2.064448,-40.791407,0.046522,1.045156,-46.089470,0.515496
2,25,Rb,155,-0.268523,0.219911,-5.146995,0.520475,1.634798,-19.028453,0.949217,1.240968,-1.351254,0.573281
3,42,Rb,14,-0.105659,0.350745,-0.569877,0.469327,1.447153,-1.564730,0.120692,1.044371,-0.960000,0.430876
4,52,Sb,2,-0.163117,0.330940,-0.033333,0.580056,2.063069,-0.033333,1.000000,1.032258,0.366667,-0.548387